catched better error messages

diff --git a/auto-submission/aws-createLeaderboardSubmission b/auto-submission/aws-createLeaderboardSubmission
--- a/auto-submission/aws-createLeaderboardSubmission
+++ b/auto-submission/aws-createLeaderboardSubmission
@@ -52,10 +52,23 @@ if [ $m_flag -eq 0 ]; then
   exit
 fi
 
+
 if [ $c_flag -eq 1 ]; then
-  ARN=$(./aws-listSubscribedPrivateLeaderboards |jq '.PrivateLeaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
+  LEADERBOARDS=$(./aws-listSubscribedPrivateLeaderboards)
+  echo $LEADERBOARDS | jq '.error[0]' | grep authenticate > /dev/null
+  if [ $? == 0 ]; then
+    echo $LEADERBOARDS
+    exit 1
+  fi
+  ARN=$(echo $LEADERBOARDS | jq '.PrivateLeaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
 else
-  ARN=$(./aws-listLeaderboards |jq '.Leaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
+  LEADERBOARDS=$(./aws-listLeaderboards)
+  echo $LEADERBOARDS | jq '.error[0]' | grep authenticate > /dev/null
+  if [ $? == 0 ]; then
+    echo $LEADERBOARDS
+    exit 1
+  fi
+  ARN=$(echo $LEADERBOARDS | jq '.Leaderboards[]|select(.Arn|test("'$SEASON'$"))|.Arn'|sed 's/"//g')
 fi
 
 if [ -z "$ARN" ]; then
diff --git a/auto-submission/aws-submitModel b/auto-submission/aws-submitModel
--- a/auto-submission/aws-submitModel
+++ b/auto-submission/aws-submitModel
@@ -48,15 +48,15 @@ fi
 CONFIGFILE="aws-deepracer.cf"
 
 if [ -f "$CONFIGFILE" ]; then
-        EMAIL=$(grep -i EMAIL "$CONFIGFILE" | awk -F= '{gsub(/"/, "", $2); print $2}')
+  EMAIL=$(grep -i EMAIL "$CONFIGFILE" | awk -F= '{gsub(/"/, "", $2); print $2}')
 	SUBMISSION_MAX=$(grep -i SUBMISSION_MAX $CONFIGFILE | awk -F= '{gsub(/"/, "", $2); print $2}')
 else
-        echo "The config file "$CONFIGFILE" is not found"
-        exit 1
+  echo "The config file "$CONFIGFILE" is not found"
+  exit 1
 fi
 
 if [ -z "$EMAIL" ]; then
-        read -p 'Email: ' EMAIL
+  read -p 'Email: ' EMAIL
 fi
 if [ -z "$SUBMISSION_MAX" ]; then
 	SUBMISSION_MAX=20
@@ -82,7 +82,7 @@ do
       report=$(echo "$submissionReport" | jq '.error[0]')
       if [[ $report == *auth* ]]; then
         source ./aws-authenticate
-	continue
+	      continue
       elif [ "$report" == "null" ]; then
         report="Unknown problem"
       fi
