Updated the readme file

diff --git a/auto-submission/aws-getModel b/auto-submission/aws-getModel
--- a/auto-submission/aws-getModel
+++ b/auto-submission/aws-getModel
@@ -31,6 +31,11 @@ export DATA
 
 ./aws-execCurl > .curl.result
 
+errorMessage=$(jq '.error[0]' .curl.result)
+if [ "$errorMessage" != 'null' ]; then
+  echo "$errorMessage"
+  exit 1
+fi
 DRMODEL=$(jq '.Model.ModelArtifactS3Location' .curl.result | awk '{gsub("\"", "", $1); print $1}') 
 rm -f .curl.result
 
